### ISSUE TITLE
Update otel recipes to account for changes in otel-collector docker image

### ISSUE THREAD

**Issue by darach** [tremor-rs/tremor-www#102]
The recipe docker-compose files refer to otel-collector images via a `latest` tag. The config
has changed and the `pprof` and `health_check` extensions are no longer valid so the docker
compose configuration needs to change:

```diff
diff --git a/docs/recipes/40_otel_passthrough/etc/otel/collector-config.yaml b/docs/recipes/40_otel_passthrough/etc/otel/collector-config.yaml
index 4db0a956..33b1f83e 100644
--- a/docs/recipes/40_otel_passthrough/etc/otel/collector-config.yaml
+++ b/docs/recipes/40_otel_passthrough/etc/otel/collector-config.yaml
@@ -10,14 +10,11 @@ processors:
   batch:

 extensions:
-  health_check:
-  pprof:
-    endpoint: :1888
   zpages:
     endpoint: :55679

 service:
-  extensions: [pprof, zpages, health_check]
+  extensions: [zpages]
   pipelines:
     logs:
       receivers: [otlp]
```

Discovered by Endre and reported via tremor chat - the above workaround was a quick fix for Endre - but we should really pin the version and update the otel recipes accordingly!

**Comment by Licenser** [comment]
The otel guide will be completely rewritten
