### ISSUE TITLE
Document all the available pre- and postprocessors and list them sorted alphabetically

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-www#139]
Currently we only list those preprocessors:

![Screenshot 2021-10-28 at 13 53 00](https://user-images.githubusercontent.com/1152667/139250509-9368b9ba-35ec-4108-9ee8-266e995038e6.png)

But we support this whole list:

![Screenshot 2021-10-28 at 13 54 02](https://user-images.githubusercontent.com/1152667/139250664-3486275c-8c2d-4211-8986-b64fa3254498.png)

### Missing preprocessors:

* gelf-chunking-tcp
* zstd
* ingest-ns

### Incorrectly listed preprocessors:

* xz -> xz2

Same is true for postprocessors:

### Missing postprocessors:

* zstd
* ingest-ns

### Incorrectly listed:

* xz -> xz2

Also they should be listed alphabetically.

**Comment by Licenser** [comment]
Thanks to @vickywane this is fixed :rocket:
