### ISSUE TITLE
Update monitoring walk through and remove legacy `pipeline` yaml config

### ISSUE THREAD

**Issue by darach** [tremor-rs/tremor-www#154]
The system metrics walk through still refers to the legacy `pipeline` configuration field that
was deprecated with the introduction of trickle. The walkthrough should be updated to use
tremor and trickle files and reflect any format changes.

https://www.tremor.rs/docs/operations/monitoring

**Comment by darach** [comment]
I stumbled onto this when Endre mentioned pipeline monitoring to see that this brief guide is out of date. We should probably expand on the stub walk through when we revisit the documentation and expand it to more fully cover `How do I monitor my pipeline` and `How do I monitor my tremor deployment` as it will likely introduce other topics such as customising metrics/monitoring and/or other quality of service related endeavours

**Comment by Licenser** [comment]
Ja all guides and examples use the old yaml, there is a lot of updating docs ahead

**Comment by Licenser** [comment]
This is resolved in the v12 refresh
