### ISSUE TITLE
Language Reference rewrite for v0.12 release

### ISSUE THREAD

**Issue by darach** [tremor-rs/tremor-www#168]
Rewrite the language reference based on a lightweight code generation process
that leverages the language grammar for tremor written in LALRPOP rather than
using a hand maintained EBNF file and online railroad diagram generators.

The generator has been submitted to LALRPOP as a draft PR here: https://github.com/lalrpop/lalrpop/pull/658

**Comment by Licenser** [comment]
This is resolved in the v12 refresh
