### ISSUE TITLE
Typo in the basics guide doc

### ISSUE THREAD

**Issue by palash25** [tremor-rs/tremor-www#288]
![termor](https://user-images.githubusercontent.com/21367710/218481227-5ff4b040-ef5b-4b42-9c1b-04e2da818c1c.png)

Hi I noticed this minor typo while going through the docs, the text says `To do this we, again define a new file lib/scripts.tremor `

but the code snippet mentions the wrong file name on top.

**Comment by Licenser** [comment]
thanks good catch 🚀 !
