### ISSUE TITLE
Create a CONTRIBUTING.md file for the docs repository

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-www#32]
This is an extract from the [Docs Assessment](https://github.com/cncf/techdocs/blob/main/assessments/0004-tremor.md) done by @celestehorgan

---

NOTE: we have this by now but it should be reviewed if it fits the web page standard

**Comment by darach** [comment]
Added a section on technical writing and documentation contributions to the contributors guide in this PR:

https://github.com/tremor-rs/tremor-www/pull/79

The CONTRIBUTING.md will be added as a separate PR so we can reference the content in the guide.

**Comment by darach** [comment]
Fixed by #79 
Fixed by #80

**Comment by darach** [comment]
Done
