### ISSUE TITLE
Develop a case study or other content around Wayfair's use of Tremor

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-www#35]
This is an extract from the [Docs Assessment](https://github.com/cncf/techdocs/blob/main/assessments/0004-tremor.md) done by @celestehorgan

---

to give users a tangible example of what they can do with the project

**Comment by darach** [comment]
We made this blog articles instead of adding a case studies section to the website.

**Comment by Licenser** [comment]
huzza!
