### ISSUE TITLE
Reorganize your documentation's information architecture

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-www#37]
This is an extract from the [Docs Assessment](https://github.com/cncf/techdocs/blob/main/assessments/0004-tremor.md) done by @celestehorgan

---

In addition to the suggestions above, I recommend an overall reorganization of the documentation, along the lines of:

- Docs
    - Overview (renamed from Architecture Overview)
    - Using Tremor 
        - subpages as described previously 
    - Artifacts 
    - Tremor Query 
    - Tremor Script
    - Examples (renamed from Workshops)
    - API Reference
    - Glossary
    - FAQ (moved from top level navigation)

**Comment by bchen28** [comment]
A parallel issue is collapsing the community folder into docs and having a more centralized documentation hierarchy. Currently a lot of content relating to documentation, such as scripting and development tools, is sitting in the community folder. A possible example is shown in the following: 

- docs (folder) 
    - Getting Started 
    - Docs
        - Overview
        - Model 
            - Processing
            - 
        - Tremor Query 
        - Tremor Script 
        - Examples 
        - API 
        - Glossary 
    - Community
        - RFCs
        - Contributing 
        - Governance
        - Events
    - Blog
    - Chat
    - FAQ

**Comment by Licenser** [comment]
I'm not convinced that is a good idea, the community section and the documentation are very different beasts and targeted at a different audience. items like the blog, or the link to the chat don't really have a place in them either. Getting started, is a bit of a in between but I could see a good reason for it to live within the documentation.

**Comment by bchen28** [comment]
Keeping them separate is also fine, the main thing I would argue for is a clear demarcation between information stored in docs and in community (mainly filtering more technical info out of community). Having concepts explained such as codecs and connectivity in the community section contributes to a feel of scattered information and often cover duplicate info.

**Comment by darach** [comment]
Closing based on the major info arch refactoring done for v0.12. Lets open a fresh ticket if/when the info arch needs revisiting again.
