### ISSUE TITLE
Syntax diagrams do not work on the dark theme

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-www#44]
For the dark theme, syntax diagrams are not readable as the arrows blend into the background color.

![image](https://user-images.githubusercontent.com/119093/133417644-c6b1957f-cb7b-4e58-b652-96c0679fc3ea.png)

**Comment by Shashank-Jha** [comment]
I would like to work on this issue.

Idea ->
Improve the dark-mode theme to improve the readability.

**Comment by darach** [comment]
Hi @Shashank-Jha,

We're hopeless with `ux` so always super appreciative of an expert guide and hand. We have a new ( draft ) language reference code generation tool [here](https://github.com/lalrpop/lalrpop/pull/658) that we are rolling into our work in progress `0.12` release [here](https://github.com/tremor-rs/tremor-runtime/blob/main/Makefile#L73-L145) that will be invoked via our docs CI process [here](https://github.com/tremor-rs/tremor-www/blob/mob-v12-refresh/Makefile#L34-L42).

Reach out if you need anything!

Cheers,

Darach.

**Comment by Licenser** [comment]
This is resolved in the 012 refresh
