### ISSUE TITLE
On the new website, the tremor icon is squashed when the window is not wide enough

### ISSUE THREAD

**Issue by craig-lancaster** [tremor-rs/tremor-www#63]
![image](https://user-images.githubusercontent.com/90869691/133679834-8444fb8a-ac9b-4676-8930-d7c1e0c9ce08.png)

The image of the logo at the top left corner of the page disappears when the window is quite narrow, and looks as expected when the window is wide enough, but in between those two extremes it is distorted. I was viewing on the current build of Microsoft Edge, and the problem reproduced with the current version of chrome too., both on a recent insider build of Windows 11.

**Comment by darach** [comment]
Oh the horror 😱 - thanks for reporting this @craig-lancaster - we owe you a puppy! 👍
