### ISSUE TITLE
Redirect `docs.tremor.rs` to `www.tremor.rs/docs`

### ISSUE THREAD

**Issue by marioortizmanero** [tremor-rs/tremor-www#73]
It'd be nice if someone could configure the domain to redirect `docs.tremor.rs/<PATH>` to `www.tremor.rs/docs/<PATH>` to not break previous links to the docs.

**Comment by Licenser** [comment]
We did set up a redirect today but the path's changed so that's really not a option :(

**Comment by marioortizmanero** [comment]
Yes, it's so close. It redirects `https://docs.tremor.rs/artefacts/offramps/` to `https://www.tremor.rs/docs/index/artefacts/offramps/` instead of  `https://www.tremor.rs/docs/artefacts/offramps/` (the `index` breaks it).

But yeah maybe it's not that easy

**Comment by Licenser** [comment]
since there are a lot more changes than just that and more to come, rewriting isn't practical we'd need to make a special rule for nearly every page.
