### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by skoech** [tremor-rs/tremor-www#76]
Due to the redesign/migration, there are a lot of broken internal links that need to be fixed.

Frequent broken links are linking to:
- /faqs/
- /docs/
- /docs/course/#/2

This is the exhaustive list of all broken links found:

- [ ] On source page path = /404.html:

   -> linking to /faqs/

- [ ] On source page path = /:
   -> linking to /faqs/

- [ ] On source page path = /api/0:
   -> linking to /faqs/

- [ ] On source page path = /blog:
   -> linking to /docs/
   -> linking to /docs/course/#/2 (resolved as: /docs/course/)
   -> linking to /faqs/

- [ ] On source page path = /blog/2020/02/22/welcome:
   -> linking to /faqs/

- [ ] On source page path = /blog/2020/03/06/influx-perf:
   -> linking to /faqs/

- [ ] On source page path = /blog/2020/03/31/rust-and-tell:
   -> linking to /faqs/

- [ ] On source page path = /blog/2020/08/06/to-async-or-not-to-async:
   -> linking to /faqs/

- [ ] On source page path = /blog/2020/10/16/v09-release:
   -> linking to /faqs/

- [ ] On source page path = /blog/2021/06/29/T17-LFX-Blog-Jigyasa-gcloud:
   -> linking to /docs/course/#/2 (resolved as: /docs/course/)
   -> linking to /docs/workshop/examples/20_transient_gd/
   -> linking to /docs/workshop/examples/21_persistent_gd/
   -> linking to /faqs/

- [ ] On source page path = /blog/2021/07/06/Blog-Rohit-Property-Based-Testing:
   -> linking to /docs/tremor-script/#patch (resolved as: /docs/tremor-script/)
   -> linking to /faqs/

- [ ] On source page path = /blog/archive:
   -> linking to /faqs/

- [ ] On source page path = /blog/LFX-Blog-Nupur:
   -> linking to /docs/
   -> linking to /faqs/

- [ ] On source page path = /blog/tags:
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/announcement:
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/cncf:
   -> linking to /docs/
   -> linking to /docs/course/#/2 (resolved as: /docs/course/)
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/codecs:
   -> linking to /docs/
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/connectors:
   -> linking to /docs/course/#/2 (resolved as: /docs/course/)
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/dev:
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/gpc:
   -> linking to /docs/course/#/2 (resolved as: /docs/course/)
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/hello:
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/mentorship:
   -> linking to /docs/
   -> linking to /docs/course/#/2 (resolved as: /docs/course/)
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/open-source:
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/perf:
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/releases:
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/rust:
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/talks:
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/testing:
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/tremorscript:
   -> linking to /faqs/

- [ ] On source page path = /blog/tags/welcome:
   -> linking to /faqs/

- [ ] On source page path = /community/tags:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/tags:
   -> linking to /faqs/

- [ ] On source page path = /docs/tags:
   -> linking to /faqs/

- [ ] On source page path = /quick-start:
   -> linking to /faqs/

- [ ] On source page path = /rfc/tags:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/artefacts/codecs:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/artefacts/offramps:
   -> linking to codecs.md#json (resolved as: /docs/next/artefacts/codecs.md)
   -> linking to ./onramps.md#rest (resolved as: /docs/next/artefacts/onramps.md)
   -> linking to ../operations/linked-transports.md (resolved as: /docs/next/operations/linked-transports.md)
   -> linking to /faqs/

- [ ] On source page path = /docs/next/artefacts/onramps:
   -> linking to ../scripting/tremor-script/stdlib/tremor/origin.md (resolved as: /docs/next/scripting/tremor-script/stdlib/tremor/origin.md)
   -> linking to /faqs/

- [ ] On source page path = /docs/next/artefacts/postprocessors:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/artefacts/preprocessors:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/ConstraintsLimitations:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/glossary:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/history:
   -> linking to scripting/tremor-script/stdlib/tremor/chash.md (resolved as: /docs/next/scripting/tremor-script/stdlib/tremor/chash.md)
   -> linking to operations/cli.md (resolved as: /docs/next/operations/cli.md)
   -> linking to /faqs/

- [ ] On source page path = /docs/next/index:
   -> linking to operations/cli.md (resolved as: /docs/next/operations/cli.md)
   -> linking to /api
   -> linking to /faqs/

- [ ] On source page path = /docs/next/operations/configuration:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/operations/configuration-walkthrough:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/operations/gdcb:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/operations/linked-transports:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/operations/monitoring:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/overview:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/bridges_lt_http_ws/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/configurator/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/filter/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/grafana/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/influx/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/kafka_elastic_correlation/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/kafka_gd/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/logstash/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/otel_elastic_apm/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/otel_jaeger/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/otel_passthrough/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/otel_prometheus/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/otel_zipkin/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/passthrough/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/persistent_gd/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/polling_alerts/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/postgres_timescaledb/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/proxies_lt_http/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/proxies_lt_ws/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/quota_service/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/reverse_proxy_load_balancing/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/roundrobin/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/servers_lt_http/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/servers_lt_ws/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/syslog_udp_dns/README:
   -> linking to ../14_syslog_udp/ (resolved as: /docs/next/recipes/14_syslog_udp/)
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/syslog_udp/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/transform/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/transient_gd/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/recipes/validate/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/ pp:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/modules:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-query/functions:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-query/functions/stats:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-query/functions/win:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-query/index:
   -> linking to ../tremor-script/stdlib/tremor/origin.md (resolved as: /docs/next/scripting/tremor-script/stdlib/tremor/origin.md)
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-query/operators:
   -> linking to /faqs/

- [ ]On source page path = /docs/next/scripting/tremor-query/recipes:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-query/walkthrough:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/extractors/base64:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/extractors/cidr:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/extractors/datetime:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/extractors/dissect:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/extractors/glob:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/extractors/grok:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/extractors/index:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/extractors/influx:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/extractors/json:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/extractors/kv:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/extractors/regex:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/functions:
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/index:
   -> linking to stdlib/std/integer.md (resolved as: /docs/next/scripting/tremor-script/stdlib/std/integer.md)
   -> linking to stdlib/std/float.md (resolved as: /docs/next/scripting/tremor-script/stdlib/std/float.md)
   -> linking to stdlib/std/string.md (resolved as: /docs/next/scripting/tremor-script/stdlib/std/string.md)
   -> linking to stdlib/std/array.md (resolved as: /docs/next/scripting/tremor-script/stdlib/std/array.md)
   -> linking to stdlib/std/record.md (resolved as: /docs/next/scripting/tremor-script/stdlib/std/record.md)
   -> linking to stdlib/std/binary.md (resolved as: /docs/next/scripting/tremor-script/stdlib/std/binary.md)
   -> linking to stdlib/std/string.md#into_binarybytes (resolved as: /docs/next/scripting/tremor-script/stdlib/std/string.md)
   -> linking to stdlib/std/string.md#from_utf8_lossybytes (resolved as: /docs/next/scripting/tremor-script/stdlib/std/string.md)
   -> linking to stdlib/std/base64.md (resolved as: /docs/next/scripting/tremor-script/stdlib/std/base64.md)
   -> linking to /docs/tremor-query/#select-queries (resolved as: /docs/tremor-query/)
   -> linking to /faqs/

- [ ] On source page path = /docs/next/scripting/tremor-script/recipes:
   -> linking to stdlib/std/array.md#pusharray-element (resolved as: /docs/next/scripting/tremor-script/stdlib/std/array.md)
   -> linking to stdlib/std/random.md (resolved as: /docs/next/scripting/tremor-script/stdlib/std/random.md)
   -> linking to stdlib/std/type.md#is_nullvalue (resolved as: /docs/next/scripting/tremor-script/stdlib/std/type.md)
   -> linking to /faqs/

- [ ] On source page path = /community/community:
   -> linking to /faqs/

- [ ] On source page path = /community/development/benchmarking:
   -> linking to /faqs/

- [ ] On source page path = /community/development/benchmarks/LogstashBenchmark:
   -> linking to /faqs/

- [ ] On source page path = /community/development/debugging:
   -> linking to /faqs/

- [ ] On source page path = /community/development/internal/running-docusaurus:
   -> linking to /faqs/

- [ ] On source page path = /community/development/internal/transform:
   -> linking to /faqs/

- [ ] On source page path = /community/development/investigations:
   -> linking to /faqs/

- [ ] On source page path = /community/development/profiling:
   -> linking to /faqs/

- [ ] On source page path = /community/development/quick-start:
   -> linking to /faqs/

- [ ] On source page path = /community/development/testing:
   -> linking to /faqs/

- [ ] On source page path = /community/faqs:
   -> linking to /faqs/

- [ ] On source page path = /community/getting-started/about:
   -> linking to /faqs/

- [ ] On source page path = /community/getting-started/codecs:
   -> linking to h/docs/artefacts/artefacts/postprocessors/#length-prefixerd (resolved as: /community/getting-started/h/docs/artefacts/artefacts/postprocessors/)
   -> linking to /faqs/

- [ ] On source page path = /community/getting-started/connectivity:
   -> linking to /faqs/

- [ ] On source page path = /community/getting-started/getting-started:
   -> linking to /docs/workshop/examples/10_logstash/README
   -> linking to /docs/workshop/examples/11_influx/README
   -> linking to /faqs/

- [ ] On source page path = /community/getting-started/install:
   -> linking to /docs/development/quick-start/
   -> linking to /faqs/

- [ ] On source page path = /community/getting-started/scripting:
   -> linking to /docs/tremor-script/#match (resolved as: /docs/tremor-script/)
   -> linking to /docs
   -> linking to /docs/tremor-query
   -> linking to /docs/artefacts/operators
   -> linking to /faqs/

- [ ] On source page path = /community/getting-started/specialize:
   -> linking to /docs/artefacts/operators#runtimetremor (resolved as: /docs/artefacts/operators)
   -> linking to /docs/artefacts/operators#grouperbucket (resolved as: /docs/artefacts/operators)
   -> linking to /docs/artefacts/operators#generic::backpressure (resolved as: /docs/artefacts/operators)
   -> linking to /docs/artefacts/operators#generic::batch (resolved as: /docs/artefacts/operators)
   -> linking to /docs/artefacts/operators#passthrough (resolved as: /docs/artefacts/operators)
   -> linking to /docs/artefacts/operators#debughistory (resolved as: /docs/artefacts/operators)
   -> linking to /docs/artefacts/
   -> linking to /faqs/

- [ ] On source page path = /community/getting-started/tooling:
   -> linking to /faqs/

- [ ] On source page path = /community/governance:
   -> linking to /faqs/

- [ ] On source page path = /community/governance/CII:
   -> linking to /faqs/

- [ ] On source page path = /community/governance/CodeofConduct:
   -> linking to /docs/CodeOfConduct
   -> linking to /faqs/

- [ ] On source page path = /community/governance/Contributing:
   -> linking to /docs/CodeOfConduct
   -> linking to /docs/policies/security
   -> linking to /docs/development/quick-start/
   -> linking to /faqs/

- [ ] On source page path = /community/governance/policies/security:
   -> linking to /faqs/

- [ ] On source page path = /community/teams:
   -> linking to /faqs/

- [ ] On source page path = /docs/artefacts/codecs:
   -> linking to /faqs/

- [ ] On source page path = /docs/artefacts/offramps:
   -> linking to codecs.md#json (resolved as: /docs/artefacts/codecs.md)
   -> linking to ./onramps.md#rest (resolved as: /docs/artefacts/onramps.md)
   -> linking to ../operations/linked-transports.md (resolved as: /docs/operations/linked-transports.md)
   -> linking to /faqs/

- [ ] On source page path = /docs/artefacts/onramps:
   -> linking to /faqs/

- [ ] On source page path = /docs/artefacts/postprocessors:
   -> linking to /faqs/

- [ ] On source page path = /docs/artefacts/preprocessors:
   -> linking to /faqs/

- [ ] On source page path = /docs/ConstraintsLimitations:
   -> linking to /faqs/

- [ ] On source page path = /docs/glossary:
   -> linking to /faqs/

- [ ] On source page path = /docs/history:
   -> linking to /faqs/

- [ ] On source page path = /docs/index:
   -> linking to /api
   -> linking to /faqs/

- [ ] On source page path = /docs/operations/cli:
   -> linking to /faqs/

- [ ] On source page path = /docs/operations/configuration:
   -> linking to /faqs/

- [ ] On source page path = /docs/operations/configuration-walkthrough:
   -> linking to /faqs/

- [ ] On source page path = /docs/operations/gdcb:
   -> linking to /faqs/

- [ ] On source page path = /docs/operations/linked-transports:
   -> linking to /faqs/

- [ ] On source page path = /docs/operations/monitoring:
   -> linking to /faqs/

- [ ] On source page path = /docs/overview:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/bridges_lt_http_ws/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/configurator/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/filter/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/grafana/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/influx/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/kafka_elastic_correlation/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/kafka_gd/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/logstash/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/otel_elastic_apm/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/otel_jaeger/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/otel_passthrough/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/otel_prometheus/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/otel_zipkin/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/passthrough/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/persistent_gd/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/polling_alerts/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/postgres_timescaledb/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/proxies_lt_http/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/proxies_lt_ws/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/quota_service/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/reverse_proxy_load_balancing/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/roundrobin/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/servers_lt_http/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/servers_lt_ws/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/syslog_udp_dns/README:
   -> linking to ../14_syslog_udp/ (resolved as: /docs/recipes/14_syslog_udp/)
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/syslog_udp/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/transform/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/transient_gd/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/recipes/validate/README:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-query/functions:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-query/functions/stats:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-query/functions/win:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-query/index:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-query/modules:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-query/operators:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-query/pp:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-query/recipes:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-query/walkthrough:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/extractors:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/extractors/base64:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/extractors/cidr:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/extractors/datetime:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/extractors/dissect:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/extractors/glob:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/extractors/grok:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/extractors/influx:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/extractors/json:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/extractors/kv:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/extractors/regex:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/functions:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/index:
   -> linking to /docs/tremor-query/#select-queries (resolved as: /docs/tremor-query/)
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/modules:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/pp:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/recipes:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/cncf:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/cncf/otel:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/cncf/otel/logs:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/cncf/otel/logs/severity:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/cncf/otel/logs/traceflags:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/cncf/otel/metrics:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/cncf/otel/metrics/temporality:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/cncf/otel/span_id:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/cncf/otel/trace:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/cncf/otel/trace_id:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/cncf/otel/trace/spankind:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/cncf/otel/trace/status:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/array:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/base64:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/binary:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/float:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/integer:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/json:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/math:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/random:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/range:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/re:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/record:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/string:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/test:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/type:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/std/url:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/tremor:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/tremor/chash:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/tremor/origin:
   -> linking to /faqs/

- [ ] On source page path = /docs/tremor-script/stdlib/tremor/system:
   -> linking to /faqs/

- [ ] On source page path = /rfc/accepted/pipeline-state-mechanism:
   -> linking to /faqs/

- [ ] On source page path = /rfc/accepted/plugin-development-kit:
   -> linking to wasmtime (resolved as: /rfc/accepted/wasmtime)
   -> linking to /faqs/

- [ ] On source page path = /rfc/accepted/ramp-interface:
   -> linking to /faqs/

- [ ] On source page path = /rfc/accepted/sliding-window-mechanism:
   -> linking to /faqs/

- [ ] On source page path = /rfc/implemented/circuit-breaker-mechanism:
   -> linking to /faqs/

- [ ] On source page path = /rfc/implemented/correlation:
   -> linking to 0003-linked-transports/ (resolved as: /rfc/implemented/0003-linked-transports/)
   -> linking to /faqs/

- [ ] On source page path = /rfc/implemented/linked-transports:
   -> linking to /faqs/

- [ ] On source page path = /rfc/implemented/modularity:
   -> linking to /faqs/

- [ ] On source page path = /rfc/implemented/onramp-postgres:
   -> linking to /faqs/

- [ ] On source page path = /rfc/implemented/pipeline-optimizations:
   -> linking to /faqs/

- [ ] On source page path = /rfc/implemented/remove-actix-from-tremor-runtime:
   -> linking to /faqs/

- [ ] On source page path = /rfc/implemented/string-interpolation:
   -> linking to /faqs/

- [ ] On source page path = /rfc/index:
   -> linking to process/libs_changes (resolved as: /rfc/process/libs_changes)
   -> linking to process/0000-template/ (resolved as: /rfc/process/0000-template/)
   -> linking to /faqs/

- [ ] On source page path = /rfc/process/api_changes:
   -> linking to /faqs/

- [ ] On source page path = /rfc/process/arch_changes:
   -> linking to /faqs/

- [ ] On source page path = /rfc/process/lang_changes:
   -> linking to /faqs/

- [ ] On source page path = /rfc/process/lib_changes:
   -> linking to /faqs/

- [ ] On source page path = /rfc/process/template:
   -> linking to /faqs/

**Comment by Licenser** [comment]
This is resolved in the v12 refresh
