### ISSUE TITLE
cover in dark mode and on small screens looks off

### ISSUE THREAD

**Issue by Licenser** [tremor-rs/tremor-www#99]
It seems to be transparent, probably messed up the color instead of gray went for transparent :) oopsie

![grafik](https://user-images.githubusercontent.com/119093/135690716-a43c3ab1-f7bb-4143-b676-7da0502fe14a.png)

**Comment by Shashank-Jha** [comment]
@Licenser I would like to work on this, I'll try to resolve the issue :)

**Comment by Licenser** [comment]
That's great! Go for it :) we appreciate it.

**Comment by Licenser** [comment]
this is resolved Thank you @Shashank-Jha
